module.exports = function(theaters) {
  /* movieFilter takes a data structure containing theater information in the following format:
  [theater]
    L> google maps data about theater
      L> time to drive to theater
      L> directions to theater
    L> movies playing at theater
      L> showtimes for that movie

  It returns a list of objects like this:
  [
    { showTime:             ...
      movieName:            ...
      theaterName:          ...
      driveTimeToTheater:   ...
      directionsToTheater:  ...
    },
    { showTime:             ...
      movieName:            ...
      theaterName:          ...
      driveTimeToTheater:   ...
      directionsToTheater:  ...
    },
    ...
    ...
  ]
  */
  return {}

}